export const memberDetails = [
    {
      name: "Temidire Owoeye",
      phone: "09073210998",
      assignedTo: "olumide",
      label: "will attend service",
      status: "soul lost",
      modified: "10th July 2024",
      id: 1,
    },
    {
      name: "Daniel King",
      phone: "09073210998",
      assignedTo: "olumide",
      label: "will attend service",
      status: "soul lost",
      modified: "10th July 2024",
      id: 2,
    },
    {
      name: "Yagami Light",
      phone: "09073210998",
      assignedTo: "olumide",
      label: "will attend service",
      status: "soul lost",
      modified: "10th July 2024",
      id: 3,
    },
    {
      name: "Tanjiro Kamado",
      phone: "09073210998",
      assignedTo: "olumide",
      label: "will attend service",
      status: "soul lost",
      modified: "10th July 2024",
      id: 4,
    },
  ];